include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: rke2-test-values
    file: '/pipelines/bigbang.yaml'

variables:
  PIPELINE_REPO_BRANCH: rke2-test-values
  DEBUG_ENABLED: "true"
