{{- if .Values.addons.velero.enabled.plugins.csi }}
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-volumesnapshotclass
  annotations:
    # Optional annotation to set this VolumeSnapshotClass as default
    snapshot.storage.kubernetes.io/is-default-class: "true"
  labels:
    # Required label for Velero
    velero.io/csi-volumesnapshot-class: "true"
driver: ebs.csi.aws.com
deletionPolicy: Delete
{{- end }}
